### ISSUE TITLE
about lab0_task3

### ISSUE THREAD

**Issue by Shelby-xiasj** [FDUCSLG/OS-24Fall-FDU#2]
![image](https://github.com/user-attachments/assets/10a55084-f817-48ed-8e66-d2ef1d895b6f)
![image](https://github.com/user-attachments/assets/7e6a6aec-0592-4e9f-82a0-a76a8ded421f)
> 请问为什么elearning上pdf的版本和在线文档上获取.bss的起始地址和结束地址的方式不同，似乎后者有些问题，memset会卡住，可能是由于访问越界？

**Comment by Boreas618** [comment]
抱歉，请以[在线文档](https://osh.fducslg.com)为准，助教忘记修改PDF版本上的错误了。

另外请注意，在线文档里的data和edata是data段的始末地址，而不是bss段的始末地址。

**Comment by Shelby-xiasj** [comment]
明白了，谢谢老师
